# ASP.NET Core (.NET Framework)

# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

name: 1.0$(Rev:.r)

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: NuGetCommand@2
  displayName: 'Restore from Nuget.org and EmmersionLearning feeds'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '2ee1cde5-9787-4e91-b498-e30a43c5d914'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    projects: 'DistributedToolsServer/DistributedToolsServer.csproj'
    versioningScheme: 'byBuildNumber'
    arguments: '-c Release -o $(build.artifactstagingdirectory)/server /p:VersionPrefix=$(build.buildNumber)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: DistributedToolsServer'
  inputs:
    PathToPublish: '$(build.artifactstagingdirectory)/server'
    ArtifactName: 'DistributedToolsServer'
